namespace PixelWallE.Language.Tokens;

public enum TokenType
{  
    //Single character token
    LEFT_PAREN, RIGHT_PAREN,LEFT_BRACKET,RIGHT_BRACKET, COMMA, NEW_LINE, 
    //Operators token
    ASSIGNMENT, MINUS, PLUS, DIVIDE, MULTIPLY, MODULO, EXPONENTIAL,
    EQUAL,
    NOT_EQUAL, NOT, 
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    AND, OR,
    //Comment token
    COMENNT, DOT,
    
    //Literals
    IDENTIFIER, STRING, NUMBER,
    
    //KEYWORD
	FALSE,TRUE, COLOR, LIST, INTTYPE, BOOLTYPE, STRINGTYPE,
		//COMMAND
		 DRAWCIRCLE, DRAWLINE, DRAWRECTANGLE, FILL, GOTO, SIZE, SPAWN,PRINT,RESPAWN,
    //LIST COMMAND
         ADD,REMOVEAT,CLEAR,LENGHT,
		//FUNCTION
    GETACTUALX,GETACTUALY,GETCANVASSIZE,GETCOLORCOUNT,ISBRUSHCOLOR,ISBRUSHSIZE,ISCANVASCOLOR, 
    
    //End of file
    EOF,
    //End of Line
    EOL,
    
    UNKNOW
}